### PR TITLE
Added back button in ProfileSection

### LINKED ISSUE #4: Add a Back Button in ProfileScreen
WhatsApp Image 2023-10-02 at 6 58 01 PM

### PR DESCRIPTION
**Pull request by shlok-2003**
resolves #4

### CODE REVIEW

**Comment by shlok-2003** [comment]
Hey @SanjaySargam, done with the implementation. Have a look

**Comment by SanjaySargam** [comment]
@shlok-2003 Ok I'll check and merge it
Btw Thanks for your contribution 🎉

**Comment by shlok-2003** [comment]
YesI am attaching the image below
WhatsApp Image 2023-10-12 at 19 02 07_0fdcad5b

**Comment by shlok-2003** [comment]
I have modified the layout. Tell if any changes are needed

**Comment by SanjaySargam** [comment]
> I have modified the layout. Tell if any changes are needed

Please delete arrow.png coz it is no longer required

**Pull request merged**
