### PR TITLE
Chore: Refactor all the files for correct lint and formatting options

### PR DESCRIPTION
**Pull request by devsargam**
As specified in `.eslintrc` & `.prettierrc`, this PR fixes all the issues that were present in the codebase.
NOTE: This commit doesn't change any code behavior but only enforce proper formatting

### CODE REVIEW

**Comment by devsargam** [comment]
Fixes #5

**Comment by devsargam** [comment]
@SanjaySargam can you please review the changes?

**Comment by devsargam** [comment]
Also I suggest you use a precommit tool like [husky](https://typicode.github.io/husky/).
It enforces all the developers working on the project to enforce necessary lint and style checking.

**Comment by SanjaySargam** [comment]
Did you testee ? 
Attach a screen record of working app

**Comment by SanjaySargam** [comment]
> Also I suggest you use a precommit tool like [husky](https://typicode.github.io/husky/).
> It enforces all the developers working on the project to enforce necessary lint and style checking.

Ok Do you want to work on it ?

**Comment by devsargam** [comment]
> Did you tested ? Attach a screen record of working app
@SanjaySargam actually no but can you do it? I am confident that I didn't break any thing since no code file was edited.
I am on a mac and setting up android or IOS was a pain without expo.

**Comment by devsargam** [comment]
> Ok Do you want to work on it ?

Yup, I can work on it

**Comment by devsargam** [comment]
@SanjaySargam any updates?

**Comment by SanjaySargam** [comment]
> > Did you tested ? Attach a screen record of working app
> 
> @SanjaySargam actually no but can you do it? I am confident that I didn't break any thing since no code file was edited.
> I am on a mac and setting up android or IOS was a pain without expo.
> 

@devsargam Test it once 
And share video

**Pull request closed without merging**
